version: '2'

services:
    #anaconda3:
     #   image: continuumio/anaconda3
    dbpg:
        image: postgres
    mysql:
        #name: mysql
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: django
            MYSQL_USER: django
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - webpage        
    web:
     # build: .
     #image: gurvinder
     #image: pythonws_web
     image: gurvinderd/anaconda3-django:v2
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - dbpg
       - mysql
     networks:
       - webpage
 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            #PMA_HOST: mysql
            #PMA_PORT: 3306
            #PMA_USER: django
            #PMA_PASSWORD: password
        restart: always
        ports:
            - "8181:80"
        #links:
        #   - mysql:mysql
        depends_on:
            - mysql
networks:
  webpage:
volumes:
    db_data: